# Generated by Django 3.2.4 on 2021-06-24 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posttagmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at'),
        ),
        migrations.AddField(
            model_name='posttagmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='posts.categorymodel', verbose_name='category'),
        ),
    ]
