# Generated by Django 3.2.4 on 2021-06-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='postinfo',
            field=models.TextField(max_length=500, verbose_name='postinfo'),
        ),
    ]
