# Generated by Django 3.2.4 on 2021-06-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_postmodel_postinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='postinfo',
            field=models.TextField(max_length=150, verbose_name='postinfo'),
        ),
    ]
