# Generated by Django 3.2.4 on 2021-06-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_postmodel_postinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='blog_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
