# Generated by Django 3.2.4 on 2021-07-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_commentmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='user',
        ),
    ]
