# Generated by Django 3.2.4 on 2021-06-17 04:53

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=django.utils.translation.ugettext_lazy)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('company', models.CharField(max_length=50, verbose_name='company')),
                ('select', models.CharField(max_length=50, verbose_name='select')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
