# Generated by Django 3.2.4 on 2021-07-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='view',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
