# Generated by Django 3.2.4 on 2021-07-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactmodel_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='view',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
