# Generated by Django 3.2.4 on 2021-06-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210624_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='phone'),
        ),
    ]
