# Generated by Django 3.2.4 on 2021-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profilemodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='facebook',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='twitter',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='username'),
        ),
    ]
