# Generated by Django 3.2.4 on 2021-06-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profilemodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
